project:
  type: website

execute: 
  freeze: auto

format:
  html:
    theme:
      light: [morph, Theme/morph_custom.scss]
      dark:  [slate, Theme/slate_custom.scss]

profile:
  default: beg
  group: [beg, int, exp, root]

