project:
  output-dir: ./docs/int
  render:
    - index.qmd
    - "Qmd Files/Getting Started/*.qmd"


website:
  title: "Getting Started with Quarto"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Example Page"
        href: "beg/Qmd Files/Example Page/index_beg.html"
      - text: "Getting Started"
        href: "Qmd Files/Getting Started/getting_started.qmd"
      - text: "Tipps and Tricks for Quarto Users"
        href: "exp/Qmd Files/Tipps and Tricks/index_exp.html"
  sidebar:
    - id: getting-started-sidebar
      style: docked
      collapse-level: 1
      contents:
        - href: "Qmd Files/Getting Started/getting_started.qmd"
          text: "Overview"
        - section: Creating a Quarto Website
          contents:
            - href: "Qmd Files/Getting Started/beg_website_1.qmd"
              text: What you need
            - href: "Qmd Files/Getting Started/beg_website_2.qmd"
              text: Create a Website
            - href: "Qmd Files/Getting Started/beg_website_3.qmd"
              text: Publish a Website
        - section: Creating an Exercise Sheet with Quarto
          contents:
            - href: "Qmd Files/Getting Started/beg_exercise_1.qmd"
              text: What you need
            - href: "Qmd Files/Getting Started/beg_exercise_2.qmd"
              text: Create an Exercise Sheet
            - href: "Qmd Files/Getting Started/beg_exercise_3.qmd"
              text: Other Output Formats
        - section: Creating a Quarto Book
          contents:
            - href: "Qmd Files/Getting Started/beg_book_1.qmd"
              text: What you need
            - href: "Qmd Files/Getting Started/beg_book_2.qmd"
              text: Create a Book
        - section: Interactive Code
          contents:
            - href: "Qmd Files/Getting Started/beg_extensions.qmd"
              text: Interactive Python with Pyodide

format:
  html:
    code-tools: true