project:
  output-dir: ./docs/exp
  render:
    - index.qmd
    - Qmd Files/Tipps and Tricks/*.qmd

website:
  title: "Quarto Tipps and Tricks"
  page-navigation: true
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Example Page"
        href: "beg/Qmd Files/Example Page/index_beg.html"
      - text: "Getting Started"
        href: "int/Qmd Files/Getting Started/getting_started.html"
      - text: "Tipps and Tricks for Quarto Users"
        href: "Qmd Files/Tipps and Tricks/index_exp.qmd"
  sidebar:
    - id: tips-sidebar
      style: docked
      contents:
        - href: "Qmd Files/Tipps and Tricks/index_exp.qmd"
          text: "What's covered & What you should know already"
        - href: "Qmd Files/Tipps and Tricks/exp_yml.qmd"
          text: The YML File
        - href: "Qmd Files/Tipps and Tricks/exp_qmd.qmd"
          text: The QMD File
        - href: "Qmd Files/Tipps and Tricks/exp_extensions.qmd"
          text: Extensions
        - href: "Qmd Files/Tipps and Tricks/exp_multilanguage.qmd"
          text: Multilanguage Projects
        - href: "Qmd Files/Tipps and Tricks/exp_cheatsheet.qmd"
          text: Cheatsheet

format:
  html:
    toc: true
    code-tools: true
